version: '3'

services:
  vault:
    image:  vault:1.13.3
    container_name: vault
    volumes:
      - ./config:/vault/config
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
      VAULT_API_ADDR: http://0.0.0.0:8200
    command: vault server -config=/vault/config/vault.hcl
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "500m"
    network_mode: bridge